name: Setup

inputs:
  aws-role-access:
    description: AWS Role Access
    required: true
  ssh-private-key:
    description: SSH Private Key
    required: true

outputs:
  kamal-registry-password:
    description: Kamal Registry Password
    value: ${{ steps.login-ecr.outputs.docker_password_<YOUR_AWS_ACCOUNT_ID>_dkr_ecr_us_east_1_amazonaws_com }}

runs:
  using: composite
  steps:
    - uses: ruby/setup-ruby@v1
      env:
        BUNDLE_GEMFILE: ./Gemfile
      with:
        ruby-version: .ruby-version
        bundler-cache: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role-access }}
        role-session-name: samplerolesession
        aws-region: us-east-1
        mask-aws-account-id: "true"

    - name: login-to-aws-ecr
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: "true"
